# Generated by Django 4.2.27 on 2026-02-10 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0003_alter_issue_status'),
        ('penalties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='issue_uuid',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='uuid',
        ),
        migrations.AddField(
            model_name='penalty',
            name='issue',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='penalty', to='issues.issue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
